version: '3'

services:
  app:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    volumes:
      - "./:/workspace/app"
    ports:
      - "8088:8080" # from local machine the app will be accessible at http://localhost:8088
  redis:
    image: redis
    ports:
      - "6380:6379"